config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'welcome/index'

  root 'welcome#index'
  get 'gallery' => 'gallery#index'

  get 'zoo/:name' => 'zoo#index', as: :zoo

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/image.rb
class Image < ActiveRecord::Base
	mount_uploader :file, FileUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
	def index
		@images = Image.all
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index


	end

end

app/controllers/zoo_controller.rb
class ZooController < ApplicationController

	def index

		case params[:name]
		when 'anatomy'
			@unityLevel = "Anatomy.unity3d"
		when 'danceParty'
			@unityLevel = "Dance Party.unity3d"
		when 'special'
			@unityLevel = "Special.unity3d"
		when 'secretScene'
			@unityLevel = "Secret Scene.unity3d"
		when 'jonsScene'
			@unityLevel = "Jons Scene.unity3d"
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper

end

app/helpers/zoo_helper.rb
module ZooHelper

end

app/views/gallery/index.html.erb
<ul class="rslides">
	<% @images.each do |image| %>
		<li> <%= image_tag image.file_url, :alt => image.alt_text %> </li>
 	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Dmitry Tarasev - Software Engineer</title>
  <%= favicon_link_tag '/favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= nav_bar :fixed => :top do %>
    <%= menu_group do %>
        <%= menu_item "Home", root_path %>
        <%= menu_item "Photo Gallery", gallery_path %>
        <%= drop_down "Web Zoo" do %>
          <% ["Anatomy", "Dance Party", "Secret Scene", "Special", "Jon's Scene"].each do |item| %>
            <%= menu_item item, zoo_path(:name => item.gsub(" ", "_").gsub("'", "").camelize(:lower)) %>
          <% end %>
        <% end %>
    <% end %>
<% end %>
<%= yield %>



<% (0..VERTICAL_LASER_LINES).each do |i| %>

  <div id= "vert-laser-line-<%="#{i}"%>"></div>

<% end %>

<% (0..HORIZONTAL_LASER_LINES).each do |i| %>

  <div id= "horiz-laser-line-<%="#{i}"%>"></div>

<% end %>

</body>
</html>

app/views/welcome/index.html.erb
<div class="intro_header" > Hi there! My name is Dmitry.</div>


<p> <%= link_to image_tag("GitHub-Mark-120px-plus.png", alt: "Visit my GitHub"), "https://github.com/Photomotoz/" , :class => "github_button" %></p>

app/views/zoo/index.html.erb
<p class="header"><span>Unity Web Player | </span>Web Zoo</p>
<div class="content">
	<div id="unityPlayer">
		<div class="missing">
			<a href="http://unity3d.com/webplayer/" title="Unity Web Player. Install now!">
				<img alt="Unity Web Player. Install now!" src="http://webplayer.unity3d.com/installation/getunity.png" width="193" height="63" />
			</a>
		</div>
	</div>
</div>
<p class="footer">&laquo; created with <a href="http://unity3d.com/unity/" title="Go to unity3d.com">Unity</a> &raquo;</p>

<script type="text/javascript">

	loadLevel("<%= asset_path @unityLevel%>");
</script>